### PR TITLE
Upgrade samples to 1.1 Preview 1 and upgrade .NET apps to .NET 6

### PR DESCRIPTION
**Pull request by rohanp-msft**
## Description

Upgrade samples to 1.1 Preview 1 and upgrade .NET apps to .NET 6.

## Target Release

1.1 Preview 1.

## How verified
Used VS 2022. x64 debug.

## Checklist

- [X] Samples build and run using the Visual Studio versions listed in the [Windows development docs](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=stable#2-install-visual-studio).
  VS 2022 coverage is explained below.
  VS 2019: Just CPP apps since .NET 6 doesn't apply to VS 2019. Just x64 debug done - that's sufficient given the nature of this change.
- [X] Samples build and run on all supported platforms (x64, x86, ARM64) and configurations (Debug, Release).
  Built and ran on VS 2022 x64 debug. Other VS2022 x86 and x64 combos were just built by pipeline build. Locally just built ARM64 with VS 2022. That's sufficient given the nature of this change.
- [X] Samples set the minimum supported OS version to Windows 10 version 1809.
- [X] Samples build clean with no warnings or errors.
- [X] I have commented on my PR `/azp run` to have the CI build run on my branch. This must be done right before merging to ensure the build is up to date and accurate.

### CODE REVIEW

**Review by axelandrejs — APPROVED** [review]

**Review by huichen123 — APPROVED** [review]

**Comment by huichen123** [comment]
> 		{6CB98632-6091-412F-AB5D-D6F7000073A6}.Release|arm64.ActiveCfg = Release|x64

arm64

---
Refers to: Samples/ResourceManagement/cs-wpf/wpf_packaged_app.sln:29 in f57e5ae. [](commit_id = f57e5ae639d939d544af761ac352c5c338f3226c, deletion_comment = False)

**Pull request merged**
