### PR TITLE
[Samples]: Add Windows Widgets C# Authoring sample

### PR DESCRIPTION
**Pull request by beervoley**
## Description

Add Windows Widgets C# Authoring sample.

## Target Release

1.2 stable

## Checklist

- [x] Samples build and run using the Visual Studio versions listed in the [Windows development docs](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=stable#2-install-visual-studio).
- [x] Samples build and run on all supported platforms (x64, x86, ARM64) and configurations (Debug, Release).
- [x] Samples set the minimum supported OS version to Windows 10 version 1809.
- [x] Samples build clean with no warnings or errors.
- [x] **[For new samples]**: Samples have completed the [sample guidelines checklist](https://github.com/microsoft/WindowsAppSDK-Samples/blob/main/docs/samples-guidelines.md#checklist) and follow [standardization/naming guidelines](https://github.com/microsoft/WindowsAppSDK-Samples/blob/main/docs/samples-guidelines.md#standardization-and-naming).
- [x] If I am onboarding a new feature, then I must have correctly setup a new CI pipeline for my feature with the correct triggers and path filters laid out in the "Onboarding Samples CI Pipeline for new feature" section in samples-guidelines.md.
- [x] I have commented on my PR `/azp run SamplesCI-<FeatureName>` to have the CI build run on my branch for each of my FeatureName my PR is modifying. This must be done on the latest commit on the PR before merging to ensure the build is up to date and accurate. Warning: the PR will not block automatically if this is not run due to '/azp run' limitation on triggering more than 10 pipelines.

### CODE REVIEW

**Comment by peterjuras** [comment]
Hi @beervoley.

thank you for creating & working on this sample. I tried it out and while it runs successfully, the C# steps for "Converting sample from Console to Windows application" do not work. It might be that more is required in addition to just changing the output type to a Windows Application.

In general, what would be even more helpful is to have a sample widget provider with a WinUI 3 app. I have a very hard time transferring the implementation of this sample to build a WinUI 3 app that also offers widgets (and where both the widget providers & the app can access the same data).

**Comment by beervoley** [comment]
> Hi @beervoley.
> 
> thank you for creating & working on this sample. I tried it out and while it runs successfully, the C# steps for "Converting sample from Console to Windows application" do not work. It might be that more is required in addition to just changing the output type to a Windows Application.
> 
> In general, what would be even more helpful is to have a sample widget provider with a WinUI 3 app. I have a very hard time transferring the implementation of this sample to build a WinUI 3 app that also offers widgets (and where both the widget providers & the app can access the same data).

hi @peterjuras, thanks for trying the sample : ) You're right - once the app type is set to Windows Application - the provider will exit almost immediately. I have added an event to wait on in that case : )

As for your other question, integrating the widgets into an existing application is as simple as taking the code from this sample & appxmanifest and adding it to your application directly. Your application will simply need to declare an extension in its appxmanifest to declare that it has widgets you want to show. After that's done, you'll need to register a widget provider with COM (i.e. `RegistrationManager<WidgetProvider>.RegisterProvider()` in the sample) and that will be it. Once your application is deployed - you'll be able to interact with your widgets that are part of your winui3 application.

**Review by MikeHillberg — APPROVED** [review]

**Pull request merged**
