### PR TITLE
[Build] Updated WASDK Sample apps to consume 1.6-Stable

### PR DESCRIPTION
**Pull request by alexlamtest**
Updating the Release/1.6-Stable branch on the WASDK Sample apps repo to consume WASDK 1.6-Stable.

## Description

Please include a summary of the change and/or which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Target Release

Please specify which release this PR should align with. e.g., 1.0, 1.1, 1.1 Preview 1.

## Checklist

- [ ] Samples build and run using the Visual Studio versions listed in the [Windows development docs](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=stable#2-install-visual-studio).
- [ ] Samples build and run on all supported platforms (x64, x86, ARM64) and configurations (Debug, Release).
- [ ] Samples set the minimum supported OS version to Windows 10 version 1809.
- [ ] Samples build clean with no warnings or errors.
- [ ] **[For new samples]**: Samples have completed the [sample guidelines checklist](https://github.com/microsoft/WindowsAppSDK-Samples/blob/main/docs/samples-guidelines.md#checklist) and follow [standardization/naming guidelines](https://github.com/microsoft/WindowsAppSDK-Samples/blob/main/docs/samples-guidelines.md#standardization-and-naming).
- [ ] If I am onboarding a new feature, then I must have correctly setup a new CI pipeline for my feature with the correct triggers and path filters laid out in the "Onboarding Samples CI Pipeline for new feature" section in samples-guidelines.md.
- [ ] I have commented on my PR `/azp run SamplesCI-<FeatureName>` to have the CI build run on my branch for each of my FeatureName my PR is modifying. This must be done on the latest commit on the PR before merging to ensure the build is up to date and accurate. Warning: the PR will not block automatically if this is not run due to '/azp run' limitation on triggering more than 10 pipelines.

### CODE REVIEW

**Review by kythant — APPROVED** [review]

**Comment by JesseCol** [comment]
Huh, I would have thought that you'd need to add references to the WebView2 package when you update to 1.6.  Can you confirm these projects are building OK for you?

**Comment by Scottj1s** [comment]
> Huh, I would have thought that you'd need to add references to the WebView2 package when you update to 1.6. Can you confirm these projects are building OK for you?

Agreed - this change alone should result in a build error:
22>cppwinrt : error Type 'Microsoft.Web.WebView2.Core.CoreWebView2' could not be found

**Comment by Scottj1s** [comment]
Please revert  [individual WindowsSdkPackageVersion changes](https://github.com/microsoft/WindowsAppSDK-Samples/pull/387/commits/f5017b4fc7ca9d117c0b0ae625ee4ff6e75bab2e) now, with [Directory.Build.targets](https://github.com/microsoft/WindowsAppSDK-Samples/pull/387/commits/7970b5fadade86b7aae3ae4bfeaabd312c7406dd) change

**Review by Scottj1s — APPROVED** [review]

**Comment by alexlamtest** [comment]
Agg nightly pipeline based on 1.6-Stable pointing at this private branch is all greeen:
https://microsoft.visualstudio.com/ProjectReunion/_build/results?buildId=107786893&view=results

Based on that, merging this PR.

**Pull request merged**
